<<<<<<< HEAD
name: Devgrow
=======
name: devgrow
>>>>>>> ff1488594e74c4900aa16a61db1010afde79b2ae
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  sqflite: ^2.4.2
  sqflite_common_ffi_web: ^0.4.0
  path: ^1.9.1
  provider: ^6.1.5+1
  shared_preferences: ^2.2.2
  audioplayers: ^6.5.1
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
<<<<<<< HEAD
  flutter_launcher_icons: ^0.13.1  # ✅ Tambah package untuk app icon

# ✅ Konfigurasi launcher icon
flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo.jpg"

=======
>>>>>>> ff1488594e74c4900aa16a61db1010afde79b2ae

flutter:
  uses-material-design: true

  assets:
    - assets/practicals.jpg
    - assets/syntax.jpg
    - assets/dart.jpg
    - assets/flutter.png
    - assets/flutter_category.jpg
    - assets/dart_category.jpg
    - assets/practical_category.jpg
    - assets/syntax_category.jpg
    - assets/quiz_category.jpg
    - assets/question.png
    - assets/bg_quiz.jpg
    - assets/bg_bricks.jpeg
    - assets/bg_dart_quiz.jpg
    - assets/level_1.png
    - assets/level_2.png
    - assets/level_3.png
    - assets/bg_level.jpg
    - assets/bg_quizlvl1.jpg
    - assets/stone_button.png
    - assets/quiz_button.png
    - assets/ice_button.png
    - assets/bg_lvl2.jpg
    - assets/bg_lvl3.jpg
    - assets/fire_button.png
    - assets/flutter_quiz_bg.jpg
    - assets/button_start.png
    - assets/dart_intro.png

   #sounds
    - assets/sounds/punch.mp3
    - assets/sounds/countdown.mp3
    - assets/sounds/quiz_sound.mp3
    - assets/sounds/crack.mp3


  fonts:
    - family: Minecraft
      fonts:
        - asset: assets/fonts/Minecraft.ttf