name: devgrow
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.1.0
  sqflite: ^2.4.2
  sqflite_common_ffi_web: ^0.4.0
  path: ^1.9.1
  provider: ^6.1.5+1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/practicals.jpg
    - lib/assets/syntax.jpg
    - lib/assets/dart.jpg
    - lib/assets/flutter.png
    - lib/assets/flutter_category.jpg
    - lib/assets/dart_category.jpg
    - lib/assets/practical_category.jpg
    - lib/assets/syntax_category.jpg
    - lib/assets/quiz_category.jpg
    - lib/assets/question.png
